from __future__ import annotations
from typing import Protocol

class ChannelAdapter(Protocol):
    async def send_text(self, to: str, body: str) -> dict: ...
    async def send_buttons(self, to: str, body: str, buttons: list[tuple[str, str]]) -> dict: ...
    async def request_location(self, to: str, body: str = "Please share your location.") -> dict: ...
